### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by mxsb** [Unleash/unleash-spring-boot-starter#22]
### Describe the feature request

Please add a license to the project, so companies know what they get using this project.

### Background

I have some auto config features ready to contribute, but without license I can't.

### Solution suggestions

I suggest using the Apache 2.0 license, which is used by the Java client [here](https://github.com/Unleash/unleash-client-java/blob/main/LICENSE).

**Comment by thomasheartman** [comment]
Hey! Thanks for picking up on this. That's a very good point, and I support using the same license as the Java client. @praveenpg , do you have any preferences here?

**Comment by praveenpg** [comment]
> Hey! Thanks for picking up on this. That's a very good point, and I support using the same license as the Java client. @praveenpg , do you have any preferences here?

@thomasheartman Agree, we can use the same license

**Comment by thomasheartman** [comment]
The license file has now been added. Thanks @mxsb for pointing this out 🙏🏼
