### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by GFriedrich** [Unleash/unleash-spring-boot-starter#26]
### Describe the feature request

Release a new version of the Spring Boot starter library.

### Background

The current master branch contains bugfixes for Spring Boot 3, which are not yet available on the Maven central repository.

**Comment by relnah** [comment]
Any progress here?

**Comment by b-errouane** [comment]
Appearently a new version has been pushed yesterday: https://central.sonatype.com/artifact/io.getunleash/springboot-unleash-starter/1.1.0 This uses the also new version of the core from yesterday: https://central.sonatype.com/artifact/io.getunleash/springboot-unleash-core/1.1.0
And also the new autoconfigure version from yesterday is used which should fix Spring Boot 3: https://central.sonatype.com/artifact/io.getunleash/springboot-unleash-autoconfigure/1.1.0

**Comment by chriswk** [comment]
Yes, sorry, meant to update this issue. Going to close this, 1.1.0 is available
