### ISSUE TITLE
Unable to use own InstanceId

### ISSUE THREAD

**Issue by ajdergute** [Unleash/unleash-spring-boot-starter#7]
https://github.com/Unleash/unleash-spring-boot-starter/blob/2dc91045c2bea988261a3c4e80cda6e6d652b959/springboot-unleash-autoconfigure/src/main/java/org/unleash/features/config/UnleashAutoConfiguration.java#L64

I assume the exclamation mark in this line should be removed. If I configure my instanceId a UUID is used instead.

**Comment by checketts** [comment]
Agreed. Good find

**Comment by praveenpg** [comment]
unleashProperties.getInstanceId() is the instance Id that you will be configuring.

**Comment by praveenpg** [comment]
Great find @ajdergute. I will create a PR with the change

**Comment by praveenpg** [comment]
@ajdergute Created a PR
https://github.com/Unleash/unleash-spring-boot-starter/pull/12

**Comment by ajdergute** [comment]
LGTM

**Comment by ajdergute** [comment]
Would be really nice to see this as a release on maven central.
