### ISSUE TITLE
Were are tests for this starter?

### ISSUE THREAD

**Issue by ajdergute** [Unleash/unleash-spring-boot-starter#8]
### Describe the feature request

I missed a test suite. Do you have plans to add one?

I desired I'm open to contribute tests to this project.

### Background

For instance at first I misconfigured this starter and got a meaningless NPE.

**Comment by praveenpg** [comment]
@ajdergute Thanks for bringing this up. It would be great if you can contribute tests to this. Otherwise I can start adding them some time next week.

**Comment by ajdergute** [comment]
Great! I will try some stuff, hopefully soon.
