### ISSUE TITLE
Change groupId to match groupId of unleash sdk

### ISSUE THREAD

**Issue by praveenpg** [Unleash/unleash-spring-boot-starter#9]
### Describe the feature request

Change groupId to match groupId of unleash sdk.
Currently it has groupId of the domain that I use. This needs to be changed to the domain that unleash owns as the ownership now is currently with unleash

### Background

Current groupID: net.leodb.unleash
proposed groupId: io.getunleash

**Comment by sjaanus** [comment]
@praveenpg thank you for letting us know. We will fix it shortly.

**Comment by sjaanus** [comment]
This is being solved by #10
